# Generated by Django 3.2.25 on 2025-07-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='published_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
