# Generated by Django 3.2.25 on 2025-07-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20250715_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
